name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”

jobs:
  build:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@feat/clinder
  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      id-token: write
      pages: write
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@feat/clinder